# 산포통계

In [2]:
import numpy as np
from scipy import stats
import pandas as pd

## 분산 계산

In [ ]:
x = [1, 2, 3, 4, 5]
# ddof Delta Degrees of Freedom -> 자유도 조정값 
# "표준편차를 계산할 때 분모에서 몇을 뺄 것인가?"
# ddof=1은 분모를 N이 아니라 N-1로 하라는 의미

# var = 분산(Variance)
print(np.var(x, ddof = 1)) # 분모 = n - 1 ( 5 - 1), 표본
print(np.array(x).var()) # 분모 = n
# 분모 = n , 자유도(ddof) 0:모분산인경우, 표본분산
# Series : Pandas의 1차원 데이터 구조
print(pd.Series(x).var(ddof = 0)) 

2.5
2.0
2.0


## 표준편차 계산

In [ ]:
x = [1, 2, 3, 4, 5]
# std는 Standard Deviation(표준편차)
print(np.std(x, ddof = 1))
print(np.array(x).std(ddof = 0))
print(pd.Series(x).std(ddof = 1))

1.5811388300841898
1.4142135623730951
1.5811388300841898


## 변동계수의 필요성

- 분산과 표준편차 모두 값의 스케일에 크게 영향을 받아 상대적인 산포를 보여주는데 부작합함.
- 변동 계수 = 표준편차 / 평균

In [20]:
x1 = np.array([1, 2, 3, 4, 5])
x2 = x1 * 10

print(np.std(x1,ddof = 1))
print(np.std(x2,ddof=1))

1.5811388300841898
15.811388300841896


In [7]:
print(stats.variation(x1)) # 변동 계수
print(stats.variation(x2))

0.47140452079103173
0.4714045207910317


In [8]:
print(np.std(x1, ddof = 1) / np.mean(x1))
print(np.std(x2, ddof = 1) / np.mean(x2))

0.5270462766947299
0.5270462766947299


## 스케일링
- 둘 이상의 변수의 값을 상대적으로 비교할 때 사용 

In [9]:
import numpy as np
import pandas as pd

In [10]:
x1 = np.array([1, 2, 3, 4, 5])
x2 = x1 * 10

In [11]:
x1

array([1, 2, 3, 4, 5])

In [12]:
x2

array([10, 20, 30, 40, 50])

In [ ]:
# Standard Scaling
# 평균을 0, 표준편차를 1로 변환하는 전처리 방법
z1 = (x1 - x1.mean()) / x1.std()
z2 = (x2 - x2.mean()) / x2.std()

print(z1)
print(z2)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [ ]:
# Min-max Scaling
# 0~1 사이로 변환
z1 = (x1 - x1.min()) / (x1.max() - x1.min())
z2 = (x2 - x2.min()) / (x2.max() - x2.min())

print(z1)
print(z2)

[0.   0.25 0.5  0.75 1.  ]
[0.   0.25 0.5  0.75 1.  ]


In [ ]:
# sklearn을 이용한 스케일링을 위한 데이터 준비
# 표 형태
# DataFrame은 Pandas에서 사용하는 2차원 표 형태의 데이터 구조라서
X = pd.DataFrame({"X1":[1, 2, 3, 4, 5],
    "X2": [10, 20, 30, 40, 50]})

X

,X1,X2
0,1,10
1,2,20
2,3,30
3,4,40
4,5,50


In [ ]:
# scikit learn 의 MinMaxScaler 적용
# 0 ~ 1 데이터 스크케일링함
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler() # 인스턴스화
# fit_transform(X)은 X의 스케일링 기준을 학습(fit)한 후, 그 기준으로 X를 변환(transform)하는 함수이다.
Z = scaler.fit_transform(X) # fit_transform => ndarray

pd.DataFrame(Z, columns=['X1', 'X2'])

,X1,X2
0,0.00,0.00
1,0.25,0.25
2,0.50,0.50
3,0.75,0.75
4,1.00,1.00


In [17]:
# 표준 정규분포에 따라서 데이터의 수준을 맞춤
# 표준 정규분포 : 
from sklearn.preprocessing import StandardScaler

In [18]:
ss_scaler = StandardScaler() # 인스턴스화
Z = ss_scaler.fit_transform(X) # fit_transform => ndarray
pd.DataFrame(Z, columns=['X1', 'X2'])

,X1,X2
0,-1.414214,-1.414214
1,-0.707107,-0.707107
2,0.000000,0.000000
3,0.707107,0.707107
4,1.414214,1.414214


In [19]:
# Standard scaling
from sklearn.preprocessing import StandardScaler

ss_scaler = StandardScaler() # 인스턴스화
S = ss_scaler.fit_transform(X) # fit_transform => ndarray
pd.DataFrame(S, columns=['X1', 'X2'])

,X1,X2
0,-1.414214,-1.414214
1,-0.707107,-0.707107
2,0.000000,0.000000
3,0.707107,0.707107
4,1.414214,1.414214


범위와 사분위 범위 계산

- 정규분포(np.random.normal)로 부터 무작위 샘플 만들기

- np.random.normal(0,1,1000) # [정규분포] 평균 0, 표준편차 1, 개수 1000개

In [23]:
# np.random.normal(평균, 편차, size = 갯수)
x = np.random.normal(100, 20, size = 1000)
x

array([ 75.91145656,  71.53392335,  89.36416767, 118.56181468,
        80.82459478, 107.77515856,  73.10729414, 104.95568397,
       118.9175684 , 130.22560804, 124.08015823,  88.54605055,
       129.15620175, 117.47308696, 144.03818413, 101.8795811 ,
       115.5075401 ,  82.34638639, 101.43291143, 137.82301448,
       102.23060916, 104.95330656, 101.31498966,  55.69222818,
       117.54643249, 107.1169438 , 111.13885792,  97.7952974 ,
       110.23710668, 107.34976447, 125.39060618,  72.18639115,
       100.6268425 ,  89.2287994 , 103.48080081,  93.11724944,
        77.24984301, 100.06581015,  88.94254625,  94.32475056,
       103.60255384, 126.06484776,  56.23619008,  92.32170175,
       114.37508963, 120.81858045,  80.10743758, 120.28939159,
       113.7459277 , 100.00191493,  73.16384677,  96.69395616,
        99.77307308,  81.93065813,  98.60363557,  89.18940223,
        97.84099691, 119.3331161 ,  86.9450761 , 103.67426634,
        93.64566478, 102.22646739,  88.93568101,  74.28

In [24]:
print(np.ptp(x))
print(np.max(x) - np.min(x))

118.18654178769334
118.18654178769334


In [25]:
print(np.quantile(x, 0.75) - np.quantile(x, 0.25))
print(stats.iqr(x))

25.91583383592878
25.915833835928765
